import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { getPool } from '@/lib/db';

export const dynamic = 'force-dynamic';

export async function GET(request: NextRequest) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const userId = Number(session.user.id);
  const format = request.nextUrl.searchParams.get('format') || 'markdown';
  const pool = getPool();

  // Get creator profile
  const profileRes = await pool.query(
    'SELECT * FROM creator_profiles WHERE user_id = $1',
    [userId]
  );
  const profile = profileRes.rows[0];

  // Get all playbook sections
  const { rows: sections } = await pool.query(`
    SELECT * FROM playbook_sections
    WHERE user_id = $1
    ORDER BY updated_at DESC
  `, [userId]);

  if (sections.length === 0) {
    return NextResponse.json({ error: 'No playbook sections to export' }, { status: 400 });
  }

  if (format === 'markdown') {
    const md = generateMarkdown(sections, profile);
    return new NextResponse(md, {
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': 'attachment; filename="hook-playbook.md"',
      },
    });
  }

  return NextResponse.json({ error: 'Unsupported format. Use: markdown' }, { status: 400 });
}

interface PlaybookSection {
  title: string;
  hook_type: string | null;
  niche: string | null;
  templates: { script: string; example_filled?: string }[] | string;
  why_it_works: string | null;
  source_post_ids: number[] | string | null;
  generated_at: string | null;
}

interface CreatorProfile {
  niche: string | null;
  content_style: string | null;
  target_audience: string | null;
  unique_angle: string | null;
}

function generateMarkdown(sections: PlaybookSection[], profile: CreatorProfile | null): string {
  const lines: string[] = [];

  lines.push('# Your Hook Playbook');
  lines.push('');
  lines.push(`*Generated by Peakr Hook Intelligence*`);
  lines.push('');

  if (profile) {
    lines.push('## Your Creator Profile');
    lines.push('');
    if (profile.niche) lines.push(`- **Niche:** ${profile.niche}`);
    if (profile.content_style) lines.push(`- **Style:** ${profile.content_style}`);
    if (profile.target_audience) lines.push(`- **Audience:** ${profile.target_audience}`);
    if (profile.unique_angle) lines.push(`- **Angle:** ${profile.unique_angle}`);
    lines.push('');
    lines.push('---');
    lines.push('');
  }

  for (const section of sections) {
    lines.push(`## ${section.title || 'Untitled Section'}`);
    lines.push('');

    const label = [section.hook_type, section.niche].filter(Boolean).join(' + ');
    if (label) {
      lines.push(`*Category: ${label}*`);
      lines.push('');
    }

    const templates = typeof section.templates === 'string'
      ? JSON.parse(section.templates)
      : section.templates;

    if (Array.isArray(templates)) {
      templates.forEach((t: { script: string; example_filled?: string }, i: number) => {
        lines.push(`### Template ${i + 1}`);
        lines.push('');
        lines.push(`> ${t.script}`);
        lines.push('');
        if (t.example_filled) {
          lines.push(`**Example:** ${t.example_filled}`);
          lines.push('');
        }
      });
    }

    if (section.why_it_works) {
      lines.push(`**Why these work for you:** ${section.why_it_works}`);
      lines.push('');
    }

    lines.push('---');
    lines.push('');
  }

  lines.push(`*Exported on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*`);

  return lines.join('\n');
}
